spring.application.name=securitysystem

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.datasource.url=jdbc:h2:file:./data/securitysystem-db;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2

app.admin.username=admin
app.admin.password=CAUCqar

app.security.cookieName=QAR_SESSION
app.security.cookieSecure=false
app.security.cookieSameSite=Strict
app.security.sessionTtlMinutes=60

app.person.seedEnabled=true
app.person.seedCsv=classpath:person_seed.csv
